name: numeron
description: "Numer0n is a simple game that you can play with your friends."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_analytics: ^10.10.1
  firebase_crashlytics: ^3.5.1
  firebase_remote_config: ^4.4.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Potta_One
      fonts:
        - asset: assets/fonts/Potta_One/PottaOne-Regular.ttf
          weight: 400
    - family: Jersey_10
      fonts:
        - asset: assets/fonts/Jersey_10/Jersey10-Regular.ttf
          weight: 400
  uses-material-design: true
